export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const SEARCH = 'SEARCH';
export const PIN_SELECTED = 'PIN_SELECTED';
export const MAP_CENTER_CHANGED = 'MAP_CENTER_CHANGED';
export const MARKERS_FETCHED = 'MARKERS_FETCHED';
export const CENTER_CHANGED = 'CENTER_CHANGED';


export const FETCHED_BUSINESSES = "FETCHED_BUSINESSES";
export const FETCHING_BUSINESSES = "FETCHING_BUSINESSES";
export const FETCH_BUSINESSES_ERROR = "FETCH_BUSINESSES_ERROR";

export const GEOLOCATION_FETCHED = "GEOLOCATION_FETCHED";
export const ZOOM_CHANGED = "ZOOM_CHANGED";
export const FILTER_RANGE_CHANGED = "FILTER_RANGE_CHANGED";
