export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const SEARCH = 'SEARCH';
export const PIN_CLICKED = 'PIN_CLICKED';
export const RADIUS_CHANGED = 'RADIUS_CHANGED';
export const MAP_CENTER_CHANGED = 'MAP_CENTER_CHANGED';
export const MARKERS_FETCHED = 'MARKERS_FETCHED';
export const CENTER_CHANGED = 'CENTER_CHANGED';


export const FETCHED_BUSINESSES = "FETCHED_BUSINESSES";

export const GEOLOCATION_FETCHED = "GEOLOCATION_FETCHED";