/* global __dirname */
/* generated by unstuck-webpack */

var path = require('path');
var webpack = require('webpack');
var dir_js = path.resolve(__dirname, 'app');
var dir_css = path.resolve(__dirname, 'css');
var dir_build = path.resolve(__dirname, 'dist');
module.exports = {
    entry: [
        'webpack-dev-server/client?http://0.0.0.0:8080', // WebpackDevServer host and port
        'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors,
        'react-hot-loader/patch',
        "babel-polyfill",
        path.resolve(__dirname, 'app/index.js')
    ],
    output: {
        path: dir_build,
        filename: 'bundle.js'
    },
    resolve: {
       modulesDirectories: ['node_modules', dir_js]
    },
    plugins: [
        new webpack.NoErrorsPlugin(),
        new webpack.ProvidePlugin({
            '$': 'jquery'
        }),
        new webpack.HotModuleReplacementPlugin()
    ],
    module: {
        loaders: [
            {
                loader: 'file?name=assets[name].[ext]',
                test: /\.png($|\?)|\.woff($|\?)|\.woff2($|\?)|\.ttf($|\?)|\.eot($|\?)|\.svg($|\?)/
            },
            {
                test: /\.js($|\?)|\.jsx($|\?)/,
                include: [
                    dir_js
                ],
                loaders : ["babel"]

            },
            {
                loader: 'file?name=/[name].html',
                test: /\.html$/
            },
            {
                test: /\.s?css$/,
                loaders: ["style", "css?sourceMap", "sass?sourceMap"],
            },
            {
                test: /\.json$/,
                loader: 'json-loader'
            }
        ]
    },
    devtool: "source-map"
};
